version: "3"
services:
  db:
    container_name: go-postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_MULTIPLE_DATABASES: go_clean_architecture,go_clean_architecture_test
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./database/postgres/data:/docker-entrypoint-initdb.d
    networks:
      - clean-architecture
    restart: always

networks:
  clean-architecture:
    driver: bridge