// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injection

import (
	"github.com/arvians-id/go-clean-architecture/cmd/config"
	"github.com/arvians-id/go-clean-architecture/internal/http/controller"
	"github.com/arvians-id/go-clean-architecture/internal/http/routes"
	"github.com/arvians-id/go-clean-architecture/internal/repository"
	"github.com/arvians-id/go-clean-architecture/internal/service"
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitServerAPI(configuration config.Config) (*gin.Engine, error) {
	db, err := config.NewInitializedDatabase(configuration)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(db)
	userService := service.NewUserService(userRepository)
	userController := controller.NewUserController(userService)
	engine := routes.NewInitializedRoutes(userController)
	return engine, nil
}

// wire.go:

var userSet = wire.NewSet(repository.NewUserRepository, service.NewUserService, controller.NewUserController)
